### ISSUE TITLE
kless moved to tredoe?

### ISSUE THREAD

**Issue by dalu** [myENA/mkpasswd#1]
```
$ mkpasswd 
panic: crypt: requested crypt function is unavailable

goroutine 1 [running]:
github.com/kless/osutil/user/crypt.New(0x4, 0x6, 0x4e46b7)
	/home/darko/go/src/github.com/kless/osutil/user/crypt/crypt.go:83 +0xab
main.main()
	/home/darko/go/src/github.com/myENA/mkpasswd/mkpasswd.go:87 +0xa9a
```

when going to github.com/kless/osutil I'm being redirected to github.com/tredoe/osutil

**Comment by leprechau** [comment]
Thank you!  We've been using glide locally for awhile and it follows the redirect.  I've updated the sources and also included the glide files here.
